### PR TITLE
Configure some CI infra

### PR DESCRIPTION
**Pull request by charleskawczynski**
I'm fine with keeping the old CI tests or replacing with the new file (I did this since I already knew that the names/hooks are compatible with bors).

### CODE REVIEW

**Comment by charleskawczynski** [comment]
bors ping

**Comment by jb-mackay** [comment]
@charleskawczynski thanks for doing this! So we are on the same page -  does the ci.yml file take the place of the old workflow files? And what is the role of the .dev folder?

**Comment by charleskawczynski** [comment]
> @charleskawczynski thanks for doing this! So we are on the same page - does the ci.yml file take the place of the old workflow files? And what is the role of the .dev folder?

Yes, it does, so long there aren't any special things happening in the original unit test yaml file.

The role of the `.dev` folder adds julia formatting functionality, so that we can format files with `julia .dev/climaformat.jl .`

**Comment by jb-mackay** [comment]
> Yes, it does, so long there aren't any special things happening in the original unit test yaml file.
> 
> The role of the `.dev` folder adds julia formatting functionality, so that we can format files with `julia .dev/climaformat.jl .`

Ok, great! I don't think there is anything special in the original unit tests, so we can remove the yaml files for the workflows being replaced by `ci.yml`.

**Comment by charleskawczynski** [comment]
Done

**Comment by charleskawczynski** [comment]
With bors added, we could add branch protection to the main branch, so that developers don't accidentally push (or force push!) to the main branch. Want me to configure that?

**Review by jb-mackay — APPROVED** [review]
Thank you, Charlie! Looks great.

**Pull request merged**
