### PR TITLE
Add literate

### PR DESCRIPTION
**Pull request by christophernhill**
Adding hooks and test for Literate examples in docs/

### CODE REVIEW

**Comment by christophernhill** [comment]
@jb-mackay does this look OK for a start. The code needs some tidying, but I wanted to get Literate hooks in before tidying. 

There are quite a few non-fatal warning, not sure if Literate is running anything - but the docs do get produced?

**Comment by jb-mackay** [comment]
@christophernhill I think the Literate hooks are good, you can see the example is indeed being generated in the [docs preview](https://github.com/CliMA/CouplerMachine/tree/gh-pages/previews/PR5).

**Comment by christophernhill** [comment]
@jb-mackay is this good to merge at this stage? Thanks, Chris.

**Review by jb-mackay — APPROVED** [review]
@christophernhill I think we are good to go. Some `Base.IOError` warnings in the docs build but I'm not sure if they are having an impact; the docs build is successful and preview looks good locally.

**Pull request merged**
